### ISSUE TITLE
[ UI ] Display Emoji Support in Event Discription

### ISSUE THREAD

**Issue by TreavVasu** [ECellNitrr/ECellOfficialApp#83]
### Requirements 

- Support Emoji Display

![image](https://user-images.githubusercontent.com/16835617/200325256-13a8c4ec-78ed-44f6-8bf7-b33b851c591f.png)

**Comment by kvns07** [comment]
Sir its not emoji its due to "Special Symbol or Single Quote or apostrophe in JSON String in flutter".
https://stackoverflow.com/questions/55175961/special-symbol-or-single-quote-or-apostrophe-in-json-string-in-flutter
![SingleQuote](https://user-images.githubusercontent.com/96341560/200373882-4ba76410-8d10-4046-ae68-a85889513697.JPG)

**Comment by TreavVasu** [comment]
Ok just look onto it
